#pragma once

#include <gsfw/firmware/shared.h>

/* AUTOGENERATED BY GENFAMILIES */

/* all HT5xx devices */
#define GS_HT5_FW_MAGIC 0x0
#define GS_HT5_FW_START 0x0
#define GS_HT5_FW_CHECK_SIZE 0 /* ? */
#define GS_HT5_FW_BODY_START 0x394
#define GS_HT5_FW_FILE_SLOTS 0xc
#define GS_HT5_IMG_MAGIC 0x64a95b73
#define GS_HT5_IMG_CRYPT_SIZE 0x20
#define GS_HT5_IMG_KEY_SAMPLE 0x10
#define GS_HT5_IMG_BODY_START 0x20

/* all HT7xx devices */
#define GS_HT7_FW_MAGIC 0x43a78f39
#define GS_HT7_FW_START 0x0
#define GS_HT7_FW_CHECK_SIZE 0 /* ? */
#define GS_HT7_FW_BODY_START 0x1cc
#define GS_HT7_FW_FILE_SLOTS 0x6
#define GS_HT7_IMG_MAGIC 0x43a78f39
#define GS_HT7_IMG_CRYPT_SIZE 0x30
#define GS_HT7_IMG_KEY_SAMPLE 0x10
#define GS_HT7_IMG_BODY_START 0x200

/* all HT8xxv1 devices EXCEPT HT818 */
#define GS_HT8_DVF99_FW_MAGIC 0x23c97af9
#define GS_HT8_DVF99_FW_START 0x0
#define GS_HT8_DVF99_FW_CHECK_SIZE 0x0
#define GS_HT8_DVF99_FW_BODY_START 0x288
#define GS_HT8_DVF99_FW_FILE_SLOTS 0x7
#define GS_HT8_DVF99_IMG_MAGIC 0x23c97af9
#define GS_HT8_DVF99_IMG_CRYPT_SIZE 0x20
#define GS_HT8_DVF99_IMG_KEY_SAMPLE 0x10
#define GS_HT8_DVF99_IMG_BODY_START 0x200

/* HT818 only */
#define GS_HT8_DVF101_FW_MAGIC 0x23c97af9
#define GS_HT8_DVF101_FW_START 0x0
#define GS_HT8_DVF101_FW_CHECK_SIZE 0x20a
#define GS_HT8_DVF101_FW_BODY_START 0x4000
#define GS_HT8_DVF101_FW_FILE_SLOTS 0x7
#define GS_HT8_DVF101_IMG_MAGIC 0x23c97af9
#define GS_HT8_DVF101_IMG_CRYPT_SIZE 0x4000
#define GS_HT8_DVF101_IMG_KEY_SAMPLE 0x10
#define GS_HT8_DVF101_IMG_BODY_START 0x4000

/* all HT8xxv2 devices */
/* checksumming presumed but unknown */
/* mysterious encrypted(?) data prepended at 0x0-0x100 */
/* image encryption scheme not yet solved */
#define GS_HT8_ROCKCHIP_FW_MAGIC 0x23c97af9
#define GS_HT8_ROCKCHIP_FW_START 0x100
#define GS_HT8_ROCKCHIP_FW_CHECK_SIZE 0 /* ? */
#define GS_HT8_ROCKCHIP_FW_BODY_START 0x600
#define GS_HT8_ROCKCHIP_FW_FILE_SLOTS 0x10
#define GS_HT8_ROCKCHIP_IMG_MAGIC 0x23c97af9
#define GS_HT8_ROCKCHIP_IMG_CRYPT_SIZE 0x100
#define GS_HT8_ROCKCHIP_IMG_KEY_SAMPLE 0 /* ? */
#define GS_HT8_ROCKCHIP_IMG_BODY_START 0x100

typedef enum gs_device_family {
    gs_ht5,
    gs_ht7,
    gs_ht8_dvf99,
    gs_ht8_dvf101,
    gs_ht8_rockchip,
} gs_device_family_t;

#define GS_MAX_FAMILIES 5

extern gs_family_def_t gs_device_families[GS_MAX_FAMILIES];

extern void gs_device_families_init();

extern void ht5_family_init(gs_family_def_t* family);
extern void ht7_family_init(gs_family_def_t* family);
extern void ht8_dvf99_family_init(gs_family_def_t* family);
extern void ht8_dvf101_family_init(gs_family_def_t* family);
extern void ht8_rockchip_family_init(gs_family_def_t* family);