import fs from "fs/promises";

async function loadCSV(path) {
    const txt = (await fs.readFile(path)).toString();
    const table = txt.split("\n")
        .map(x => x.split("#")[0].trim()
            .split(",")
            .map(y => y.trim())
            .filter(y => y.length > 0)
        )
        .filter(x => x.length > 0);
    const header = table.shift();
    const list = [];
    for (const row of table) {
        const obj = {};
        for (let i = 0; i < header.length; i++) {
            obj[header[i]] = row[i];
        }
        list.push(obj);
    }
    return list;
}

function reHex(s) {
    const n = parseInt(s);
    if (isNaN(n)) {
        return `0 /* ${s} */`;
    }
    return "0x" + n.toString(16);
}

const families = await loadCSV("family.csv");
const devices = await loadCSV("device.csv");

const header = [`#pragma once

#include "firmware/shared.h"

/* AUTOGENERATED BY GENFAMILIES */
`];

const header2 = [`typedef enum gs_device_family {`];

const header3 = [""];

const code = [`#include "firmware/family_defs.h"

/* AUTOGENERATED BY GENFAMILIES */

gs_family_def_t gs_device_families[GS_MAX_FAMILIES] = {`];

const code2 = [`void gs_device_families_init() {`];

let i = 0;
for (const {
    name, notes,
    fw_magic, fw_start, fw_check_size, fw_body_start, fw_file_slots,
    img_magic, img_crypt_size, img_key_sample, img_body_start
} of families) {
    function define(key, value) {
        value = reHex(value);
        const macro = `GS_${name.toUpperCase()}_${key.toUpperCase()}`;
        header.push(`#define ${macro} ${value}`);
        code.push(`        .${key} = ${macro},`);
    }
    // get file0s for family
    const members = devices.filter(x => x.family === name);
    const file0 = members.map(x => x.file0);
    if (notes != null) {
        const snotes = notes.split(";").map(x => x.trim());
        for (const note of snotes) {
            code.push(`    /* ${note} */`);
            header.push(`/* ${note} */`);
        }
    }

    code.push(`    {
        .id = gs_${name},
        .name = "${name}",
        .members = {${members.map(x => `\n            "${x.name}"`).join(", ")}
            "\\0"
        },
`);

    define("fw_magic", fw_magic);
    code.push(`        .fw_first_file = {${file0.map(x => `\n            "${x}"`).join(", ")}
            "\\0"
        },`);
    define("fw_start", fw_start);
    define("fw_check_size", fw_check_size);
    define("fw_body_start", fw_body_start);
    define("fw_file_slots", fw_file_slots);

    code.push("");

    define("img_magic", img_magic);
    define("img_crypt_size", img_crypt_size);
    define("img_key_sample", img_key_sample);
    define("img_body_start", img_body_start);

    code.push("\n        { NULL, NULL, NULL },");
    code.push("\n        { false, false }");

    header2.push(`    gs_${name},`);

    header.push("");
    code.push("    },");

    header3.push(`extern void ${name}_family_init(gs_family_def_t* family);`);
    code2.push(`    ${name}_family_init(&gs_device_families[gs_${name}]);`);
}

header2.push(`} gs_device_family_t;

#define GS_MAX_FAMILIES ${families.length}

extern gs_family_def_t gs_device_families[GS_MAX_FAMILIES];

extern void gs_device_families_init();`);
code.push("};\n");
code2.push("}\n");

await fs.writeFile("include/firmware/family_defs.h", header.join("\n") + "\n" + header2.join("\n") + "\n" + header3.join("\n"));
await fs.writeFile("src/firmware/family_defs.c", code.join("\n") + "\n" + code2.join("\n"));