#include "firmware/family_defs.h"

/* AUTOGENERATED BY GENFAMILIES */

gs_family_def_t gs_device_families[GS_MAX_FAMILIES] = {
    /* all HT5xx devices */
    {
        .id = gs_ht5,
        .name = "ht5",
        .members = {
            "ht502", 
            "ht503"
            "\0"
        },

        .fw_magic = GS_HT5_FW_MAGIC,
        .fw_first_file = {
            "ht502boota.bin", 
            "ht503boota.bin"
            "\0"
        },
        .fw_start = GS_HT5_FW_START,
        .fw_check_size = GS_HT5_FW_CHECK_SIZE,
        .fw_body_start = GS_HT5_FW_BODY_START,
        .fw_file_slots = GS_HT5_FW_FILE_SLOTS,

        .img_magic = GS_HT5_IMG_MAGIC,
        .img_crypt_size = GS_HT5_IMG_CRYPT_SIZE,
        .img_key_sample = GS_HT5_IMG_KEY_SAMPLE,
        .img_body_start = GS_HT5_IMG_BODY_START,

        { NULL, NULL, NULL },

        { false, false }
    },
    /* all HT7xx devices */
    {
        .id = gs_ht7,
        .name = "ht7",
        .members = {
            "ht701", 
            "ht702", 
            "ht704"
            "\0"
        },

        .fw_magic = GS_HT7_FW_MAGIC,
        .fw_first_file = {
            "ht701prog.bin", 
            "ht702prog.bin", 
            "ht704prog.bin"
            "\0"
        },
        .fw_start = GS_HT7_FW_START,
        .fw_check_size = GS_HT7_FW_CHECK_SIZE,
        .fw_body_start = GS_HT7_FW_BODY_START,
        .fw_file_slots = GS_HT7_FW_FILE_SLOTS,

        .img_magic = GS_HT7_IMG_MAGIC,
        .img_crypt_size = GS_HT7_IMG_CRYPT_SIZE,
        .img_key_sample = GS_HT7_IMG_KEY_SAMPLE,
        .img_body_start = GS_HT7_IMG_BODY_START,

        { NULL, NULL, NULL },

        { false, false }
    },
    /* all HT8xxv1 devices EXCEPT HT818 */
    {
        .id = gs_ht8_dvf99,
        .name = "ht8_dvf99",
        .members = {
            "ht801", 
            "ht802", 
            "ht813", 
            "ht8xx"
            "\0"
        },

        .fw_magic = GS_HT8_DVF99_FW_MAGIC,
        .fw_first_file = {
            "ht801boot.bin", 
            "ht802boot.bin", 
            "ht813boot.bin", 
            "ht81xboot.bin"
            "\0"
        },
        .fw_start = GS_HT8_DVF99_FW_START,
        .fw_check_size = GS_HT8_DVF99_FW_CHECK_SIZE,
        .fw_body_start = GS_HT8_DVF99_FW_BODY_START,
        .fw_file_slots = GS_HT8_DVF99_FW_FILE_SLOTS,

        .img_magic = GS_HT8_DVF99_IMG_MAGIC,
        .img_crypt_size = GS_HT8_DVF99_IMG_CRYPT_SIZE,
        .img_key_sample = GS_HT8_DVF99_IMG_KEY_SAMPLE,
        .img_body_start = GS_HT8_DVF99_IMG_BODY_START,

        { NULL, NULL, NULL },

        { false, false }
    },
    /* HT818 only */
    {
        .id = gs_ht8_dvf101,
        .name = "ht8_dvf101",
        .members = {
            "ht818"
            "\0"
        },

        .fw_magic = GS_HT8_DVF101_FW_MAGIC,
        .fw_first_file = {
            "ht818boot.bin"
            "\0"
        },
        .fw_start = GS_HT8_DVF101_FW_START,
        .fw_check_size = GS_HT8_DVF101_FW_CHECK_SIZE,
        .fw_body_start = GS_HT8_DVF101_FW_BODY_START,
        .fw_file_slots = GS_HT8_DVF101_FW_FILE_SLOTS,

        .img_magic = GS_HT8_DVF101_IMG_MAGIC,
        .img_crypt_size = GS_HT8_DVF101_IMG_CRYPT_SIZE,
        .img_key_sample = GS_HT8_DVF101_IMG_KEY_SAMPLE,
        .img_body_start = GS_HT8_DVF101_IMG_BODY_START,

        { NULL, NULL, NULL },

        { false, false }
    },
    /* all HT8xxv2 devices */
    /* checksumming presumed but unknown */
    /* mysterious encrypted(?) data prepended at 0x0-0x100 */
    /* image encryption scheme not yet solved */
    {
        .id = gs_ht8_rockchip,
        .name = "ht8_rockchip",
        .members = {
            "ht80xv2", 
            "ht81xv2", 
            "ht8x1"
            "\0"
        },

        .fw_magic = GS_HT8_ROCKCHIP_FW_MAGIC,
        .fw_first_file = {
            "ht80xv2boot.bin", 
            "ht81xv2boot.bin", 
            "ht8x1boot.bin"
            "\0"
        },
        .fw_start = GS_HT8_ROCKCHIP_FW_START,
        .fw_check_size = GS_HT8_ROCKCHIP_FW_CHECK_SIZE,
        .fw_body_start = GS_HT8_ROCKCHIP_FW_BODY_START,
        .fw_file_slots = GS_HT8_ROCKCHIP_FW_FILE_SLOTS,

        .img_magic = GS_HT8_ROCKCHIP_IMG_MAGIC,
        .img_crypt_size = GS_HT8_ROCKCHIP_IMG_CRYPT_SIZE,
        .img_key_sample = GS_HT8_ROCKCHIP_IMG_KEY_SAMPLE,
        .img_body_start = GS_HT8_ROCKCHIP_IMG_BODY_START,

        { NULL, NULL, NULL },

        { false, false }
    },
};

void gs_device_families_init() {
    ht5_family_init(&gs_device_families[gs_ht5]);
    ht7_family_init(&gs_device_families[gs_ht7]);
    ht8_dvf99_family_init(&gs_device_families[gs_ht8_dvf99]);
    ht8_dvf101_family_init(&gs_device_families[gs_ht8_dvf101]);
    ht8_rockchip_family_init(&gs_device_families[gs_ht8_rockchip]);
}
